### ISSUE TITLE
Global structs on left-hand side don't compile unless referred to elsewhere first

### ISSUE THREAD

**Issue by Garydos** [KarolS/millfork#10]
Try compiling the example below to see the bug in action, but basically the compiler complains that the members of a global variable aren't defined until you use the variable elsewhere in the program, after which the program compiles fine.  
Tested on Windows using release 0.3.8.

````
//compile with -t c64
import c64_basic

struct bug {
    byte x
}

bug b

void foo (byte x) {
    byte y
    // b.x //this line prevents the bug
    // y = b.x //this line also prevents the bug
    b.x = x
}

void main() {
    foo(1)
    // putword_basic(b.x) //this line also prevents the bug
}
````

**Comment by KarolS** [comment]
Thanks for your report. I pushed a fix. It will be available in the next release.

**Comment by Garydos** [comment]
Thanks, just tested the changes myself and it looks like it's fixed!
