### ISSUE TITLE
Absolute path imports do not work

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#106]
After the fix for #89, absolute import paths no longer function.

For example:

```
// main.mfk

import folder1/test
```

```
// folder1/test2
```

```
// folder1/test

import folder1/test2
^^ Import error
```

This previously functioned prior to the relative import change. This is resolved by adding the root directory to the include directories. Is this intentional, or should the root directory always appear in the include list?

**Comment by KarolS** [comment]
This is not intentional, I'll look into it.

**Comment by KarolS** [comment]
I looked into it and indeed all of that import fixing made the root directory no longer a part of the module search path. 
I think it's better that it is, as it's very useful for any larger project and doesn't change anything for small projects.
The fix will be included in the next version, and right now the workaround is adding `-i .` parameter.
