### ISSUE TITLE
pointer/word argument can get clobbered by subsequent function calls.

### ISSUE THREAD

**Issue by Garydos** [KarolS/millfork#11]
As the title states, pointer parameters are not guaranteed to still be correct if you call another function with its own pointer/word parameter. The sample code below (which was extracted from a larger project) illustrates this problem. Compile it and you'll see that `player` gets overwritten after a nested series of function calls.

In the larger project that this example comes from, I was able to work around this bug by simply making the parameter into a global variable, thus ensuring that its value couldn't be overwritten. Another workaround I tried was first transferring the parameter variable to a static local variable, but that static local variable was overwritten as well. Maybe the compiler is optimizing memory usage incorrectly?  

Tested on Windows using release 0.3.8.
````
//compile with -t c64
import c64_basic
import stdio

struct Box {
    byte x,
    byte y,
    byte width,
    byte height
}

struct Phys_Obj {
    Box pos,
    byte xfrac,
    byte yfrac,
    sbyte xvel,
    sbyte yvel,
    byte xaccel,
    byte yaccel,
    byte xspeed,
    bool on_ground,
    bool jumping,
    bool can_jump
}

Phys_Obj player1

inline pointer get_metatile_column(word metatiles_column) {
    //This is the function where the original player pointer
    //gets corrupted.
    return pointer(metatiles_column)
}

byte get_tile(byte column, byte row) {
    byte tile
    pointer metatiles_column

    metatiles_column = get_metatile_column($0000)
    tile = $00
    return tile
}

void check_background_collis(byte screenx, byte screeny, byte spritewidth, byte spriteheight) {
    byte new_column1
    byte new_column2
    byte new_row1
    byte new_row2
    byte i
    byte limit
    byte current_tile
    
    current_tile = get_tile(0,0)
}

void check_player_collis_and_update_player_loc(pointer.Phys_Obj player) {
    sbyte temp_vel
    byte old_playerx
    byte old_playerx_frac
    byte old_playery
    byte old_playery_frac
    
    old_playerx = player1.pos.x
    old_playery = player1.pos.y    
    old_playerx_frac = player1.xfrac
    old_playery_frac = player1.yfrac

    check_background_collis(player1.pos.x, player1.pos.y, player1.pos.width, player1.pos.height)
}

inline void game_logic(pointer.Phys_Obj player) {
    player->pos.x = 0
    putword_basic(player->pos.x)
    putchar(' ')
    
    //comment out this function call and the player
    //pointer should still point to the correct location
    check_player_collis_and_update_player_loc(player)
    //after the function call, player points to garbage
    
    //expected val: 0
    //if player no longer points to player1: garbage (47 on my system)
    putword_basic(player->pos.x)
}

void main() {
    pointer.Phys_Obj player
    player = pointer.Phys_Obj(player1.addr)
    game_logic(player)
}
````

**Comment by KarolS** [comment]
Thanks for your report!

I managed to replicate the problem and I'm working on a fix. In the meantime, you can use the `-fno-variable-overlap` compiler option.

**Comment by KarolS** [comment]
A fix has been implemented, it will be available in the next release.

**Comment by Garydos** [comment]
Wow that was quick, thanks! Just compiled from the latest commit and tested it out on my larger project that had more functions with this problem and everything's working as expected now! I'd say it's fixed from where I'm standing, so I'll go ahead and close this
