### ISSUE TITLE
Other label format support?

### ISSUE THREAD

**Issue by joshop** [KarolS/millfork#128]
I've decided to rewrite my homebrew NES game in Millfork before I get too far with it in assembly, and previously used Mesen for debugging. However, according to the docs, of the label formats (`.lbl`, `.fns`, `.sym`, `.nl`), it looks like only `.fns` is supported by Mesen, and only for games with exactly 32KiB PRG-ROM does this format work, which mine does not have. Is there a way to produce other label formats (i.e. `.dbg`, `.mlb`), or will this be implemented in the future?

**Comment by KarolS** [comment]
Currently, there is no way to add custom label formats, but I'm open to adding commonly used formats to the compiler. Do you have some example files I could use for reference?

**Comment by joshop** [comment]
[Here](https://www.mesen.ca/docs/debugging/debuggerintegration.html#mesen-label-files-mlb)'s a link about the `.mlb` (Mesen labels) format that Mesen supports. There's also [this](https://github.com/bbbradsmith/NES-ca65-example), which is a sample NES ca65 project - ca65 generates `.dbg` files which are also supported by Mesen. I don't know about any other formats.

**Comment by KarolS** [comment]
Implemented in 0.3.30.
