### ISSUE TITLE
Cannot compile/include mfk file containing constants only.

### ISSUE THREAD

**Issue by bocianu** [KarolS/millfork#15]
I'm fiddling with millfork and atari dsplay lists, and I wanted to prepare some helper files with display list constants. But when file contains ONLY constants definitions, then compiler throws error during compilation, pointing out last line as an source of error. 
There is a workaround to that - you only need to add at least one variable, or function definition, and file compiles fine.
Is it forbidden on purpose?

I've attached my definition file which fails. If you will uncomment function at end, it will compile without any issues. 
[a8_dlist.zip](https://github.com/KarolS/millfork/files/3777959/a8_dlist.zip)

**Comment by KarolS** [comment]
This is not on purpose, it looks like a parser bug.

Before I fix it, I can offer a really silly workaround: make the module import itself (add `import a8_dlist`) at the end of the file.

**Comment by KarolS** [comment]
I figured out the core cause of the issue. If you have a syntactical structure that has a start tag, a list of elements, and an end tag, and the elements are separated with new lines (in particular, the whole file was such a structure), and you have any comment after the last element, it would fail to compile.

A fix is coming.
