### ISSUE TITLE
Can I change nullchar value somehow?

### ISSUE THREAD

**Issue by bocianu** [KarolS/millfork#17]
On Atari in **atasciiscr** encoding 'space' is encoded as char(0), and therefore all functions operating on null-terminated strings are unusable for this encoding.
It would be nice, to be able to change it somehow.

**Comment by KarolS** [comment]
You can change the value of nullchar with the following compiler flag:

    -DNULLCHAR=$FF

or by adding the following entry to the `[define]` section of your platform definition:

    NULLCHAR=$FF

It looks like I forgot to document this feature.

**Comment by KarolS** [comment]
That said, that doesn't change the nullchar in string literals, `"a"atasciiscrz[1]`  is still 0. You'll have to embed your new nullchar manually: `"a{xff}"atasciiscr`

Since there's a similar issue with `petscr`, I was thinking about changing nullchars for such encodings. What is a good nullchar value for atasciiscr?

**Comment by bocianu** [comment]
I don't know what is good, but i'm always using $ff as a string delimiter in atasciiscr. Works for me :)

**Comment by KarolS** [comment]
I checked and $FF is the reverse right-pointing arrow symbol, and it looks like it might be useful for some purposes. I was thinking about $DB, which is the reverse escape symbol.

![](https://i.imgur.com/jk4JjIE.png)

For petscr, I think I'll go with $E0, since it looks exactly the same as $A0.

**Comment by KarolS** [comment]
As of 0.3.12, the null terminator for `atasciiscr` is no longer 0 and I also added functions that work on strings in the `scr` encoding (which in case of Atari projects would usually be `atasciiscr`).

Closing as implemented.
