### ISSUE TITLE
Assignment operations on pointer accessors are too complex

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#24]
Attempting to pair pointer accessors with assignment operations generates a complexity error.
```
byte constant
constant = $50
word value
value = $850

pointer.word value_pointer
value_pointer = value.pointer

...

value_pointer[0] += constant
```

Results in:
```
Too complex left-hand-side expression
    value_pointer[0] += constant
```

However, the equivalent expression, `value_pointer[0] = value_pointer[0] + constant`, compiles and runs just fine.

**Comment by bsutherland** [comment]
I ran into the same issue with this code:

```
struct entity_t {
  word x, byte y,
  byte frame_i, byte frame_tick
}
array(entity_t) enemy[7]

...

enemy[i].x += 1
```

Thanks for the workaround @agg23.

**Comment by KarolS** [comment]
I've implemented most cases where the operand size is 2 and documented that larger operands do not work.
