### ISSUE TITLE
Manual variable address assignment causes conflicts

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#26]
I apologize for the many bugs I've filed in the past day. Yet here's another 😃 

I was attempting to create a repro for strange array interactions, possibly occurring when you force array types to overlap (say you want a static allocated area for use, and you overlay an array of structs on top of that). However, in doing so, I believe I discovered an even more dangerous issue resulting from manual address assignment.

```
struct Sprite {
    byte size,
    byte x,
    byte y,
    byte z
}

array(byte) simpleArray [4] @ $0
array(Sprite) sprites [20] @ $4

const array values = [5, 6, 7, 8, 9, 10, 11, 12]

void main() {
    byte i
    simpleArray[0] = 1
    simpleArray[1] = 2
    simpleArray[2] = 3
    simpleArray[3] = 4

    i = 0

    while i < 7 {
        sprites[i].size = values[i]
        sprites[i].x = values[i + 1]
        sprites[i].y = values[i + 2]
        sprites[i].z = values[i + 3]

        i += 4
    }

    while(true) {}
}

void irq() {

}

void nmi() {

}
```

This was the code I was playing with for my original repro. When this is built and the label file is generated, we find that `main$i` was assigned in the middle of that memory range.

```
__rwdata_size = $0
main = $8000
.wh__00005 = $8017
.fp__00007 = $8063
.ew__00008 = $8069
.ew__00012 = $806c
on_reset = $806d
vwait1 = $8084
vwait2 = $8089
clean_byte = $8092
irq = $80bb
on_nmi = $80bc
on_irq = $80e3
values.array = $810a
__rwdata_init_end = $8112
segment.chrrom.bank = $0
main$i = $4
__zeropage_last = $17
__zeropage_end = $18
segment.default.bank = $ff
segment.default.heapstart = $200
segment.default.length = $600
segment.default.end = $7ff
segment.chrrom.end = $1fff
segment.chrrom.length = $2000
segment.prgrom.length = $7eee
segment.prgrom.heapstart = $8000
segment.prgrom.start = $8112
segment.prgrom.end = $ffff
```

**Comment by KarolS** [comment]
Thanks for the report.

There was an issue where fixed-address objects were not taken into account when deciding which memory is available. I think this omission was to support defining overlapping windows to memory areas, but now you can achieve the same with segments, so this behaviour is at least surprising.

The fix will be a part of the next release.
