### ISSUE TITLE
Simple variable memory assignment fails

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#27]
It appears that basic scenarios don't actually assign memory addresses to variables. Compiling the following snippet will result in no variables being allocated, and therefore an entire PRG-ROM of `JMP $8000` (as there's no variables to write to).

```
byte foo
byte bar

void main() {
    foo = 123
    bar = 222

    while(true) {}
}

void irq() {

}

void nmi() {

}
```

However, this scenario succeeds as soon as you assign both to an address manually (e.g. `byte foo @ $0`).

**Comment by KarolS** [comment]
The variables `foo` and `bar` are unused, so the compiler removes them in order to save memory.

Did you plan on using those variables for debugging? As a temporary workaround, you can use arrays, as arrays are currently never optimized away.

**Comment by agg23** [comment]
The intended use case was indeed for debugging. I just happened to notice it when trying to build a minimal repro for another one of the other issues I filed. It makes sense that the variables would be optimized out, however, so I don't think there's anything to do here, except perhaps further documentation.

**Comment by KarolS** [comment]
I'm tempted to make volatile variables exempt from this optimization, but agreed, documenting this is a must.
