### ISSUE TITLE
Booleans in struct arrays are allocated, but assignment does not occur

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#28]
It appears that when arrays of structs containing boolean values are created, the complier properly calculates the size of the struct, but when attempting to assign a value to that field, the assignment does not occur.

```
struct Sprite {
    byte size,
    byte size2,
    byte size3,
    byte size4,
    bool x1,
    bool x,
    bool y,
    bool z
}

byte foo @ $0
bool bar @ $1
array(Sprite) sprites [20] @ $2

void main() {
    foo = 111
    bar = true

    sprites[0].size = 123
    sprites[0].size2 = 222
    sprites[0].x1 = false
    sprites[0].x = true
    sprites[0].y = true
    sprites[0].z = true

    while(true) {}
}

void irq() {

}

void nmi() {

}
```

| Address | Value |
| --- | --- |
| 0000 | 111 |
| 0001 | 1 |
| 0002 | 123 |
| 0003 | 222 |
| 0004 | 0 |
| 0005 | 0 |
| 0006 | 0 |
| 0007 | 0 |

While you probably shouldn't waste space in this manner instead of using bits instead, it's nice to use booleans for testing and rapid prototyping. Besides, there's no reason to expect it not to work.

**Comment by KarolS** [comment]
Thanks for your report. 
I nailed it down to assigning the literal `true` via any pointer-like thing on 6502 targets, other instances are not affected by this particular problem.
The fix will be available in the next release.
