### ISSUE TITLE
Support logical NOT in boolean expressions

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#29]
Currently, logical NOT (traditionally `!`) is not listed as a supported operator, and simple trial an error shows that it will not compile at the moment. This can be trivially substituted with `value == false` if used with an `if`, but is less trivial for boolean assignment.

```
bool foo
byte output @ $1

void main() {
    foo = false

    if !foo {
        output = 1
    }

    while(true) {}
}

void irq() {

}

void nmi() {

}
```

```
ERROR: (repro4.mfk:4:1) Failed to parse the module `repro4` in repro4.mfk
       void main() {
       ^
ERROR: (repro4.mfk:7:8) Syntax error
           if !foo {
              ^
ERROR: Parse failed
FATAL: Build halted due to previous errors
Exception in thread "main" java.lang.AssertionError: Build halted due to previous errors
	at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:93)
	at millfork.error.ConsoleLogger.assertNoErrors(ConsoleLogger.scala:108)
	at millfork.parser.AbstractSourceLoadingQueue.run(AbstractSourceLoadingQueue.scala:72)
	at millfork.Main$.assembleForMos(Main.scala:222)
	at millfork.Main$.main(Main.scala:90)
	at millfork.Main.main(Main.scala)
```

**Comment by KarolS** [comment]
Boolean negation is a built-in function, called `not`. https://github.com/KarolS/millfork/blob/master/docs/lang/operators.md#built-in-functions

The rationale for the lack of a separate operator comes in part from this article: https://eev.ee/blog/2016/12/01/lets-stop-copying-c/

>That single `!` is ridiculously subtle, which seems wrong to me when it makes an expression mean its polar opposite. Surely it should stick out like a sore thumb. The left parenthesis makes it worse, too; it blends in slightly as just noise. (...) The easy solution is to just spell the operator `not`.

**Comment by agg23** [comment]
My apologies. I should have seen that.
