### ISSUE TITLE
More helpful error messages ?

### ISSUE THREAD

**Issue by Nullious** [KarolS/millfork#3]
Tried to build my alien rescue project for Gameboy and received this, I only get one warning 
WARN:  Shift by zero. 
but I don't know where that is coming from as there are no line numbers or source output to show it ?
 

FATAL: What
Exception in thread "System-2" java.lang.AssertionError: What
        at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:88)
        at millfork.output.AbstractAssembler.assemble(AbstractAssembler.scala:490)
        at millfork.Main$.assembleForI80(Main.scala:293)
        at millfork.Main$.main(Main.scala:83)
        at millfork.Main.main(Main.scala)

**Comment by KarolS** [comment]
I agree that many error messages issued by the compiler are not useful.

One category is the parser errors, which will usually say "syntax error" and point somewhere only vaguely near the actual error. These will require a significant parser rewrite. I used a parser combinator library and I regret it now.

Then there are several kinds of fatal errors. Some of them are useful, but don't say where the error occurred. Some of them however, signify a situation that I didn't expect and contain a really confused and confusing message.

It looks like you encountered the case of the latter. For some reason, the compiler thinks that your initialized variables end before they start, and this is obviously wrong. It is a bug, I'll fix it soon.

**Comment by KarolS** [comment]
I managed to replicate the problem and fix it, the fix is already in the master branch

**Comment by Nullious** [comment]
Thanks I'll try and do a build tomorrow :)

**Comment by KarolS** [comment]
The fix was released in 0.3.8.
