### ISSUE TITLE
Implement KIL opcode for 6502

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#37]
It can be very useful during the development process to halt current execution outside of your debugger, perhaps in cases of unrecoverable errors. While you can accomplish this with a spin lock, this is somewhat a less elegant solution. To this end, it would be nice if one of the undocumented 6502 KIL opcodes were implemented.

**Comment by KarolS** [comment]
Thanks, now when I think of it it's a good idea to include it.

I haven't added it as it essentially kills the CPU, so I wouldn't think of any use for it, but you made me realize that it's perfect for debugging in emulated environments, as it nicely crashes the CPU and prevents anything from happening to it – even interrupts.
