### ISSUE TITLE
Cannot resolve label with >O2 optimization due to complex expression in return value

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#41]
Creating a function that returns a complex expression (in this case specifically boolean) fails when using `O3` or greater, due to optimizing out a label, but still requiring it elsewhere.

```
struct Entity {
    byte x,
    byte y
}

array(Entity) entities [2]

byte output

void main() {
    if test(0, 200) {
        output = 1
    }
}

inline bool test(byte i, byte y) {
    return y >= entities[i].y && y <= entities[i].y + 8
}

void irq() {

}

void nmi() {

}
```

Fails compiled with `-fillegals -t nes_small -g -s -fsource-in-asm -O3`

**Comment by KarolS** [comment]
Thanks for the report!

It was a bug in optimization pertaining to returning certain more complex boolean expressions involving the carry flag, caused by removal of a label that was actually still being used elsewhere. A fix has been implemented.
