### ISSUE TITLE
Optimisation suggestion

### ISSUE THREAD

**Issue by oziphantom** [KarolS/millfork#43]
Given
```
#if CBM_64 || CBM_264
    set_bg_color(white)
#endif
#if CBM_64 || CBM_264 || ZX_SPECTRUM
    set_border(red)
#endif
```
which becomes
```
;line:135:c64_vic.mfk
    LDA #1
    STA $D021
;line:139:c64_vic.mfk
    LDA #2
    STA $D020
```
could be
```
LDX #1
STX $D021
INX
STX $D020
```

**Comment by KarolS** [comment]
Thanks for the suggestion.

The optimization has been added as an extra optimization pass, running only after the function has been deemed to not be inlined, as it could conflict with other optimizations otherwise. Other similarly risky optimizations could be added in that pass too in the future.
