### ISSUE TITLE
VICE breakpoints

### ISSUE THREAD

**Issue by oziphantom** [KarolS/millfork#44]
Since going from code to exact line in ASM is difficult, could you add a breakpoint system?
the Vice labels file isn't actually a labels fill it can run "all" vice monitor commands including
break $XXXX

so in my 64tass label system, I abuse the local label system and if I find anything that has BREAK in its name, I don't add it as a label but add the address as a break $XXXX

so my code might be
* = $1000
start
lda #0
sta $d020
lda #4
_BREAK
sta $d021

this then makes a labels file as 
al $1000 .start
break $1007

allowing me to easily add and remove breakpoints from my code ready for when it auto loads the prg. 

Sadly this is probably a VICE exclusive feature.

**Comment by KarolS** [comment]
I implemented the `breakpoint()` macro, so it can be used in both assembly and Millfork code. It will be a part of the next release. Thanks for the idea.
