### ISSUE TITLE
>O2 Optimization discards inner boolean expression in macros

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#46]
Repro:

```
bool output

byte input
byte y

void main() {
    bool result
    input = 13
    y = 12
    test(result, input)

    if (result) {
        output = true
    }
}

macro void test(bool returnVal, byte x) {
    returnVal = x >= y
    returnVal = returnVal && x <= y + 8
}

void irq() {

}

void nmi() {

}
```

Compiling with `-O3` results in the following assembly:

```
main:
; 
;line:9:repro-macro-bool.mfk
;       y = 12
    LDA #$C
    STA y
; 
;line:8:repro-macro-bool.mfk
;       input = 13
    LDA #$D
    STA input
; 
;line:12:repro-macro-bool.mfk
;       if (result) {
    ; DISCARD_AF
    ; DISCARD_XF
    ; DISCARD_YF
    RTS
; 
;line
```

This does work in some capacity if you use `byte` everywhere, but it appears the optimizer is analyzing the provided values and hardcoding the results based on them (which is logical). I do believe there is more to this issue than just that, however, as I initially encountered this scenario with values that were not known at compile time.

**Comment by KarolS** [comment]
Thanks for the report. I investigated the issue and it looks like the fix for #41 broke this. I fixed it some more.
