### ISSUE TITLE
"Out of high memory" error when compiling for a8 platform

### ISSUE THREAD

**Issue by ilmenit** [KarolS/millfork#47]
The following code is compiling for c64 platform but gives error when compiling for a8. The examples for a8 (rainbow and a8_os_test) compile properly.

```C
const word size=8190;
const word sizepl=8192;

array flags[sizepl]

void main()
{
        byte iter;
	word i, prime, k, count;

        for iter,1,to,10
        {
                count = 0;
                for i,0,paralleluntil,sizepl
                {
                     flags[i] = 1
                }
                for i,0,to,size
                {
			if (flags[i]==1)
                        {
				prime = i*2 + 3;
				k = i + prime;
				while (k <= size) {
					flags[k] = 0;
					k += prime;
				}
				count+=1;
			}
		}
        }
}
```

gives:

C:\millfork-0.3.14>java -jar millfork.jar -t a8 sieve.mfk
FATAL: Out of high memory
Exception in thread "main" java.lang.AssertionError: Out of high memory
        at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:93)
        at millfork.output.VariableAllocator.allocateBytes(VariableAllocator.scala:161)
        at millfork.output.VariableAllocator.allocateBytes(VariableAllocator.scala:119)
        at millfork.env.Environment.$anonfun$allocateVariables$7(Environment.scala:199)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
        at scala.collection.mutable.HashMap$$anon$2.$anonfun$foreach$3(HashMap.scala:158)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
        at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:158)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at millfork.env.Environment.allocateVariables(Environment.scala:151)
        at millfork.output.AbstractAssembler.assemble(AbstractAssembler.scala:571)
        at millfork.Main$.assembleForMos(Main.scala:262)
        at millfork.Main$.main(Main.scala:90)
        at millfork.Main.main(Main.scala)

**Comment by KarolS** [comment]
The default platform definition for Atari is pretty bare-bones and restrictive, to say the least. It tries to fit everything between $2000 and $3FFF, so that the programs would fit on Atari 800. Obviously that's not enough for your program.

I'm not very experienced with Atari, but you could try modifying the `a8.ini` (you can put a copy of it in your project directory if you want) and change it from

    segment_default_end=$3fff

to something like

    segment_default_end=$9fff

**Comment by ilmenit** [comment]
Thanks, will try! Super-safe memory area on Atari is up between $2000-$9FFF, however with Basic disabled (which is a standard requirement for running majority of software) it's up to $BFFF.
With some additional pre-launch code you could also disable ROM to free memory use up to $CFFF or even up to the end of memory if no OS calls are required (e.g. for IO). MillFork looks very promising and I'll try to extend support of A8 platform :-)

**Comment by ilmenit** [comment]
It worked and the code compiles! Can you give some hints if this code can be optimized (keeping the same algorithm) using some special features of the language? It seems to be slower than version implemented in CC65, when compiled with:
java -jar millfork.jar -O4 -finline -t a8 sieve.mfk -o sieve-opt-mfk.xex

**Comment by KarolS** [comment]
I converted the code to C, added the benchmark framework, added Atari support to the framework, compiled the code for both C64 and Atari, using CC65 2.18 with `-Oirs -r`, Millfork 0.3.14 and the current dev version of Millfork (both with `-O4`) and Millfork is consistently faster on both platforms. 

Which version of CC65 are you using? Can you post the C code? Or the slow Millfork binary?

Here's my experiments for comparison: 
[issue47.zip](https://github.com/KarolS/millfork/files/4257504/issue47.zip)

**Comment by ilmenit** [comment]
Hi,
The CC65 version is the same one that you used.
Try the following C code - I moved the printing out of the loop not to interfere with the code in the loops.
```
#include "benchcommon.h"
#include <conio.h>
#include <stdlib.h>

#define size 8190
#define sizepl 8192

unsigned char flags[sizepl];
static char buffer[10];

void main()
{
    register unsigned char iter;
    register unsigned int i, prime, k, count;
    
    start();
    for (iter = 1; iter <= 10; iter ++)
    {
        count = 0;
        memset(flags, 1, sizeof(flags));
        for (i=0;i<=size;++i)
        {
			if (flags[i]) {
				prime = i*2 + 3;
				k = i + prime;
				while (k <= size) {
					flags[k] = 0;
					k += prime;
				}
				++count;
			}
	    }
    }
    end();
    utoa(count, buffer, 10);
    cputs(buffer);
    putchar(13);
    while(1);
}
'''

**Comment by KarolS** [comment]
Thanks, this is indeed faster. Now I know what is the issue.

So there are few things:
* what made my C version slow was not using `++x`: `x++` or `x+=1` are much slower, since CC65 cannot figure out that they're often equivalent. I should check my other C sources if I make the same mistake in there.
* what makes your C version fast is memset. Millfork detects memset-like for-loops, however it only optimizes them if the index is a byte. I'll figure something about it. 
* you can make the Millfork version a bit faster by replacing `==1` with `!=0` and by compiling with `-Of`. Still a bit slower than C, due to that memset issue mentioned above.

**Comment by ilmenit** [comment]
Very cool! Looking forward for the future improvements in Millfork! I think it's going to be mine language of choice for the next project and I hope to contribute then with improving the runtime for A8 platform. As for the other C codes in the benchmark section, I have also other proposal there for improvement https://github.com/KarolS/millfork-benchmarks/issues/2

**Comment by KarolS** [comment]
Detecting and handling memset-like loops in Millfork has been improved. I redid the benchmarks and Millfork beats C again.
