### ISSUE TITLE
when exporting symbols/labels, please support exporting all symbols ?

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [KarolS/millfork#49]
for example 
`array video_ram [$1000] @$d000
`
is not currently exported to the symbol file. would be super helpful with debuggers .

**Comment by KarolS** [comment]
Thanks for the suggestion, I just implemented it.

**Comment by KarolS** [comment]
Thanks for implementing it, I could finally test my multibyte decimal subtraction code and fix it.
