### ISSUE TITLE
Struct performance test

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [KarolS/millfork#50]
```
import stdio

#define USE_WORDS=0
array c64_screen[1000] @$400

struct game_object {
#if USE_WORDS == 1
	word xpos 
	word ypos 
	word xdirection 
	word ydirection 
#else 
	byte xpos 
	byte ypos 
	byte xdirection 
	byte ydirection 
#endif
	function.void.to.void ptr
}

array(game_object) objects[8]

#if USE_WORDS == 1
array(word) objects_xpos[8]
array(word) objects_ypos[8]
array(word) objects_xdir[8]
array(word) objects_ydir[8]
#else
array(byte) objects_xpos[8]
array(byte) objects_ypos[8]
array(byte) objects_xdir[8]
array(byte) objects_ydir[8]
#endif
array(function.void.to.void) objects_pointer[8]

const array hex_table=[$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$1,$2,$3,$4,$5,$6]
void put_bin(word offset,byte v) {
byte x 
	for x,0,until,8 {
		c64_screen[x]=$30 
		if v&(1<<(7-x)) !=0 {
			c64_screen[x]=$31
		}	
	}
}
void put_hex(word offset,byte value) {
	c64_screen[offset] = hex_table[value>>4]
	c64_screen[offset+1] = hex_table[value&$f]
}

void nullop(){
	vic_border+=1
}

asm byte cls() @$e544 extern

void main() {
byte s 
word size
pointer.game_object go
	cls()
#if USE_WORDS == 1
	putstrz("words"z)
#else 
	putstrz("bytes"z)
#endif
	new_line()
	new_line()
	putstrz("struct array with indexing"z)
	new_line()
	putstrz("objects[x].xpos"z)
	new_line()
	new_line()
	new_line()
	new_line()
	new_line()
	new_line()
	new_line()
	putstrz("struct array with pointer"z)
	new_line()
	putstrz("ptr = objects[x]"z)
	new_line()
	putstrz("ptr->xpos"z)
	new_line()
	new_line()
	new_line()
	new_line()
	putstrz("raw array"z)
	new_line()
	putstrz("objectsxpos[x]"z)

	for s,0,until,8 {
		objects[s].xpos = s<<3
		objects[s].ypos = s<<3
		objects[s].xdirection = 1
		objects[s].ydirection = 1
		objects[s].ptr = nullop.pointer
		objects_xpos[s] = s<<3
		objects_ypos[s] = s<<3
		objects_xdir[s] = 1
		objects_ydir[s] = 1
		objects_pointer[s] = nullop.pointer
	}


	asm {
		sei 
	}

	while true {		
		while vic_raster!=$40  { }
		vic_border=1 
		for s,0,until,8 {
			objects[s].xpos = objects[s].xpos + objects[s].xdirection
			objects[s].ypos = objects[s].ypos + objects[s].ydirection
			call(objects[s].ptr)
		}
		vic_border=0
		put_hex(32+(2*40),vic_raster-$40)

		while vic_raster!=$80  { }
		vic_border=3 
		for s,0,until,8 {
			go = objects[s].pointer	// can we add to GO ? is there a more efficient way here ?
			go->xpos = go->xpos + go->xdirection
			go->ypos = go->ypos + go->ydirection
			call(go->ptr)
		}
		vic_border=0
		put_hex(32+(400),vic_raster-$80)

		while vic_raster!=$b0  { }
		vic_border=2 
		for s,0,until,8 {
			objects_xpos[s] = objects_xpos[s] + objects_xdir[s]
			objects_ypos[s] = objects_ypos[s] + objects_ydir[s]
			call(objects_pointer[s])
		}

		vic_border=0
		put_hex(32+(640),vic_raster-$b0)
	}
}

```

as requested on twitter. a test of raw array's vs structs , setting USE_WORDS = 1 to use 16 bit numbers vs bytes

**Comment by agg23** [comment]
👍 

Along this line, I would encourage documenting the recommend general optimization style for Millfork. When presented with situations like this, it's very unclear whether Millfork will optimize similarly to C (which doesn't do well on low memory 8-bit machines) or if it's smarter.

**Comment by KarolS** [comment]
Thanks for the submission, I've found several places for improvement. The scores improved (assuming -O4) from 19/15/0D to 19/14/0D for bytes and from 36/25/26 to 24/24½/1C½ for words. There are still some places that could use some improvement, I'll keep working on it.

> can we add to GO ? is there a more efficient way here ?

It's broken in 0.3.16, but in the next version you should be able to do `go.raw += sizeof(game_object)`. This method scores 12 for bytes and 17 for words.

>Along this line, I would encourage documenting the recommend general optimization style for Millfork. 

@agg23 Agreed, this is something that is really needed.

**Comment by KarolS** [comment]
I found some optimizations for the bytes case. To have a baseline, I ported your example to C, using `+=` whenever it made sense. Here are the results so far:

Compiler | bytes | words
--|--|--
Millfork-0.3.16 `-O4` | 19/15/0D | 36/25/29
Millfork-dev `-O4` | 0F/12/0D | 24½/25/1D
CC65-2.16 `-Oirs -Cl` | 7E/60/3A\* | 8A/68/63
VBCC-0.9h `-O2` | 25/25/18 | 2C/2C/24
VBCC-0.9h `-O3` | 0A/0A/0A | not tested

\* When using `_ = _ + _;`, I curiously get 8F/62/**1B**.

Note that for `-O3`, vbcc manages to unroll all loops and neatly fold all addresses, so all three loops ended up using the absolute addressing mode. The program baloons to 10kB though.  
I checked and Millfork doesn't unroll those loops, even with `-Ob`.

The main reason for such variation is how the array indexing is performed: 

* VBCC uses a generic 16-bit multiplication, but is smart enough to figure out it has to do it only once per iteration

* CC65 uses a specialised function for multiplying by 6 or 10, but does it at every single access

* the upcoming Millfork version recognizes that the array is less than 256 bytes large and does an inline byte multiplication by 6 or 10, and then recognizes that the index calculations are reused and removes most of the repeats

**Comment by JettMonstersGoBoom** [comment]
really impressive results. vbcc can be a little wild with full unrolling. code just balloons

**Comment by KarolS** [comment]
I wrote some general hints here: https://millfork.readthedocs.io/en/latest/various/optimization/

I also added a new type of for loops that makes iterating over arrays of large structs easy to write and fast to execute: `for s, go: objects`
