### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [KarolS/millfork#53]
run sbt 'set test in assembly := {}' compile (sbt "set test in assembly := {}" compile on Windows) to compile the project

run sbt 'set test in assembly := {}' assembly (sbt "set test in assembly := {}" assembly on Windows) to build the

can you seperate the windows instructions out to a seperate section. eg

run sbt 'set test in assembly := {}' compile
run sbt 'set test in assembly := {}' assembly 
Windows
sbt "set test in assembly := {}" 
sbt "set test in assembly := {}"

the way github higlights these lines it's unclear. I accidentally cut the entire line and obviously it all went side-ways

**Comment by KarolS** [comment]
I fixed the formatting, I think it's better now.
