### ISSUE TITLE
FATAL: Unknown CPU achitecture: z80next

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [KarolS/millfork#55]
With latest release z80next isn't supported ? 
with 
arch=z80next

is it supported at the moment?

**Comment by KarolS** [comment]
It is supported, but under the name `zx80next`.
It's a typo and and documentation does not match the compiler. Sorry for the inconvenience.

**Comment by JettMonstersGoBoom** [comment]
I can't believe I didn't try that . Sorry I feel dumb now 😂
