### ISSUE TITLE
Complex boolean expressions silently fail

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#56]
I was able to create a repro of complex boolean expressions failing on 6502, but it seems to be partially fixed in latest master. Now my repro appears to generate the correct code, but doing the same in my project fails.

```
const byte MAX_SIZE = 4

macro void is_room_within_bounds(byte x, byte y, byte width, byte height, bool output) {
  output = x < MAX_SIZE && y < MAX_SIZE && x + width < MAX_SIZE && y + height < MAX_SIZE
}

byte temp

bool in_bounds

void main() {
    byte x
    byte y
    byte width
    byte height

    temp = 2
    x = temp
    
    temp = 3
    y = temp

    temp = 2
    width = temp

    temp = 2
    height = temp

    is_room_within_bounds(x, y, width, height, in_bounds)

    while(true) {}
}


void nmi() {
}

void irq() {

}
```

I seem to remember there previously being a limitation on the complexity of boolean expressions. Have you removed (or raised) this limitation? I'll see if I can find a working repro...

**Comment by KarolS** [comment]
I took a peek and discovered several issues:

* the 8080 target miscompiled complex boolean expressions if the outer operator was `&&`

* the 6809 target miscompiled many kinds of complex boolean expressions

* the 6502 target had an optimization bug that manifested when using complex boolean expressions that depended on the value of the carry flag

I fixed all three issues, the fix will be a part of the next release. Thanks for the report!
