### ISSUE TITLE
Combining addition with shifts breaks assignment

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#57]
Compiling the following code for 6502:

```
byte input
byte input_2
byte output

void main() {
  input = 3
  input_2 = 2

  output = (input + input_2) << 3

  while(true) {}
}

void nmi() {}

void irq() {}
```

Results in the following relevant assembly:

```
main:
    LDA #3
    STA input
    LDA #2
    STA input_2
    LDA input
    CLC
    ADC input_2
    ASL
    ASL
    ASL
.wh__00001:
.fp__00003:
    JMP .wh__00001
```

For some reason the assignment is omitted.

**Comment by KarolS** [comment]
Are you using the output variable anywhere? If not, then it has been optimized away. This happens even if you don't enable any other optimizations.

**Comment by KarolS** [comment]
If you add `-v` to the command line, then there should find a line that says `DEBUG: Removing unused global variables: output` or something like that.

**Comment by agg23** [comment]
Hm... I manage to make so many mistakes when working on repros in Millfork, apparently. You are of course correct that `output` has been optimized away. I don't know how this situation differs from my original problem in my real code base (as the output should not have been removed), but I'll close this for now.
