### ISSUE TITLE
interrupt asm function and Atari cycle sensitive DLI

### ISSUE THREAD

**Issue by zbyti** [KarolS/millfork#62]
asm function with RTI at the end it's not allowed (compiler error) without interrupt modifier but this modifier forced (incorrectly) PHR into my ASM code.

then I wrote:
```
interrupt void dli() {
  gtia_colpf2 = $de
  antic_wsync = 1
}
```
everything works but DLI interrupt it's time sensitive, because of that I want to write this in ASM and push on stack only those registers what I really used.

what I want to do is:
```
noinline asm void dli() {
 pha
 lda #$de
 sta gtia_colpf2
 sta antic_wsync
 pla
 rti
}
```

**Comment by KarolS** [comment]
Using RTI without the `interrupt` modifier is only a warning, not an error, you can ignore it.

As for extra pushes in assembly functions with the `interrupt` modifier, it's a bug, I'll fix it.
