### ISSUE TITLE
request for a new release

### ISSUE THREAD

**Issue by zbyti** [KarolS/millfork#64]
For providing examples for the A8, I am interested (mostly) in those fixes/features:

- Added local labels in assembly.
- Fix: interrupt functions written in assembly no longer have the default prologue (#62).
- Fixed the a8_os module (#58).

The new release will be useful for me to write an example of working without OS.

**Comment by zbyti** [comment]
Scala for Ubuntu (.deb) is ~700MB big ;) I'll better wait for your build :]

**Comment by zbyti** [comment]
any chance in this month?

**Comment by KarolS** [comment]
I'll release a new version as soon as I can, probably this evening or tomorrow.

**Comment by zbyti** [comment]
Thanks for the info :]

**Comment by KarolS** [comment]
0.3.22 has been released.

**Comment by zbyti** [comment]
Thank You! :+1:
