### ISSUE TITLE
Lynx/BLL header contains wrong size.

### ISSUE THREAD

**Issue by 42Bastian** [KarolS/millfork#7]
Files size in the BLL header is to small, should include the header size (10). At least for Handy.

**Comment by KarolS** [comment]
Paging @Nullious for advice

**Comment by Nullious** [comment]
Ah is that currently possible? To add simple math support to sizes ? The header size included does look like a requirement ( to be honest in my tests it worked on Handy )

**Comment by KarolS** [comment]
Currently, it's not possible, but I'll add it in the next update.

**Comment by 42Bastian** [comment]
> 
> 
> Ah is that currently possible? To add simple math support to sizes ? The header size included does look like a requirement ( to be honest in my tests it worked on Handy )

I modified your Lynx example a little bit and saw that the colors where wrong. Checking it in handybug I saw that the last 10 bytes of the palette where missing.

So if it works or not depends upon what is last in the .o file.

I am not used with mfk so I see no workaround yet.

**Comment by KarolS** [comment]
0.3.10 has been released and contains the fix.
