### ISSUE TITLE
Can this be used to convert between label formats?

### ISSUE THREAD

**Issue by chexo3** [KarolS/millfork#70]
I have some labels for a favorite homebrew game of mine that the developers recently released. Unfortunately not all of them are in the format that I can use. It's an NES game, Micro Mages. No source code, just the labels. We have among other formats, a .lbl file, a lua script containing the labels in some form, and a file ending in .nes.ram.nl. .nl being the format for FCEUX labels. So I'm not sure what's going on with these labels.

**Comment by KarolS** [comment]
Sorry, this is totally out of scope of this project.

.nl files should be loadable in FCEUX, .lua files should be loadable in BizHawk, I don't know which emulator uses the .lbl files.

If the .lbl file looks like this: `label = $8000`, then you can change the file extension to .fns and it will load in Mesen and probably some other emulators as well.

**Comment by chexo3** [comment]
Thank you for your help, sorry for the out of scope question. To be honest I wasn't sure entirely what scope this project falls under. Re-reading the README has been illuminating.
