### ISSUE TITLE
documentation - correction needed

### ISSUE THREAD

**Issue by zbyti** [KarolS/millfork#72]
https://millfork.readthedocs.io/en/latest/lang/functions/

is:
`extern asm void chkout(byte register(a) char) @ $FFD2`
should:
`asm void chkout(byte register(a) char) @ $FFD2 extern`

**Comment by KarolS** [comment]
Thanks for noticing!

Funnily enough, I also sometimes get it wrong when coding in Millfork. Too much C influence, I guess.
