### ISSUE TITLE
Arguments with function pointers

### ISSUE THREAD

**Issue by coslor** [KarolS/millfork#86]
I'm not sure whether this is a real issue, or I'm just not understanding how things are supposed to work, so my apologies ahead of time if I'm just confused.. 

My issue is with function pointers, which would come in quite handy with the architecture of the game I'm writing. Specifically, [the docs](https://karols.github.io/millfork/lang/functions.html) say:

> Non-macro, non-interrupt functions which have max one parameter of size max 2 bytes and return void or a value of size max 2 bytes, can be accessed via a pointer.

...and there's an example of an FP for a void 0-arg function. So far, so good. 

What I can't figure out is how 1-argument calls are supposed to work. For one thing, I can't seem to get the syntax right. A simple example like:
```
import stdio

void f(byte b) {
    putword(b)
}

void main() {
	function.byte.to.void p
	p=f.pointer
	call(p)	
}
```
...gets me a result of:
`Invalid function pointer type: function.byte.to.void
           call(p)`

I can't even figure out how I'd make the call if I could get it to compile, since call() doesn't accept any arguments other than the FP. So, am I just dense, or is there an issue here? If I am being stupid, I'd appreciate a simple example of using a function pointer successfully for a 1-arg function. Thanks!

**Comment by KarolS** [comment]
The syntax for what you want is `call(p, 1)`. I'll add it to the documentation.
Thanks for pointing this omission out!

**Comment by coslor** [comment]
And thank you for the quick response. However, there must be some other piece of it that I'm missing, because when I try to compile that code, I get:
>ERROR: (function_ptr_test.mfk:10:10) Invalid number of parameters for function `call`

Could we be dealing with a version issue here? I'm running 0.3.22. Has this issue been fixed in a daily or something?

**Comment by KarolS** [comment]
This should work, but maybe I missed some corner case. What is your target platform?

**Comment by coslor** [comment]
My target platform is c64.

In case it might help, here's some more context:

- My Java version is:
> java version "1.8.0_221"
>Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
>Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

- I'm running Windows 10

- Adding the **-vvv** option gives me the attached output:
[output.txt](https://github.com/KarolS/millfork/files/5540468/output.txt)

- I usually provide more options than this, but I can duplicate the error with a very minimal command line:
`java -jar c:\Users\chris\millfork-0.3.22\millfork.jar function_ptr_test.mfk`
>INFO:  No platform selected, defaulting to `c64`
>ERROR: (function_ptr_test.mfk:10:10) Invalid number of parameters for function `call`
>           call(p,1)
>                ^
>ERROR: Codegen failed
>FATAL: Build halted due to previous errors
>Exception in thread "main" java.lang.AssertionError: Build halted due to previous errors
>        at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:94)
>        at millfork.error.ConsoleLogger.assertNoErrors(ConsoleLogger.scala:109)
>        at millfork.Main$.assembleForMos(Main.scala:296)
>        at millfork.Main$.main(Main.scala:105)
>        at millfork.Main.main(Main.scala)

As I said, I'm seeing the failure with 0.3.22. What version are you seeing the above code successfully compile with?

**Comment by KarolS** [comment]
I checked what triggers this problem and it's bug. Pointers to functions with a parameter currently work only if the call function is in a subexpression and optimizations are disabled.

Which is exactly the only case I covered in the unit tests.

I'll fix it soon, and I think I'll release a new version in few days.

Thanks for finding it!

**Comment by coslor** [comment]
And thank you for tracking it down! I like Millfork a lot, and it's great to see that it's still being maintained and updated so actively. Also, my Scala skills are crazy rusty, so it would have taken me forever to track it down :-)

**Comment by coslor** [comment]
Just checking in: have you had any chance to take a look at this bug?

**Comment by KarolS** [comment]
I was just wrapping up the latest release that, among other things, fixes this bug.
